### ISSUE TITLE
no left side panel and other problems

### ISSUE THREAD

**Issue by jsbien** [jsbien/djview4shapes#1]
Compiles succesfully, but no left side panel and no main window highlighting when clicking in the right panel.

The first problem looks like the one already reported: 
https://bitbucket.org/mrudolf/djview-shapes/issues/10/no-shape-display-in-the-left-panel

The second problem was not observed earlier.

**Comment by trufanov-nok** [comment]
Hi,
The panel is working. You just need to resize it and content appears. I'll send a pull request to fix this. Highlighting is working too.

**Comment by jsbien** [comment]
trufanov-nok: Thank you very much!
