### ISSUE TITLE
Crosscompiling no longer works

### ISSUE THREAD

**Issue by jsbien** [jsbien/djview4shapes#4]
[crosscompile-errors.zip](https://github.com/jsbien/djview4shapes/files/14071354/crosscompile-errors.zip)
Before the second run the djvulibre source has been edited to remove "register".
[djvulibre_x86_64-w64-mingw32.static.gz](https://github.com/jsbien/djview4shapes/files/14072104/djvulibre_x86_64-w64-mingw32.static.gz)

**Comment by trufanov-nok** [comment]
The error is:
```
In file included from /home/jsbien/work/djview4shapes_versje/orig4test/djview4shapes/src/mxe/usr/x86_64-w64-mingw32.static/include/mmsystem.h:26,
                 from /home/jsbien/work/djview4shapes_versje/orig4test/djview4shapes/src/mxe/usr/x86_64-w64-mingw32.static/include/windows.h:86,
                 from ../../djvulibre-3.5.28/libdjvu/atomic.h:59,
                 from ../../djvulibre-3.5.28/libdjvu/GSmartPointer.h:98,
                 from ../../djvulibre-3.5.28/libdjvu/JPEGDecoder.h:71,
                 from ../../djvulibre-3.5.28/libdjvu/JPEGDecoder.cpp:83:
/home/jsbien/work/djview4shapes_versje/orig4test/djview4shapes/src/mxe/usr/x86_64-w64-mingw32.static/include/mmiscapi.h:75:62: error: 'INT32' has not been declared
   75 | LONG WINAPI sndOpenSound(LPCWSTR EventName, LPCWSTR AppName, INT32 Flags, PHANDLE FileHandle);
      |                                                              ^~~~~
make[2]: *** [Makefile:1004: libdjvulibre_la-JPEGDecoder.lo] Error 1
```

In fact INT32 is defined in `mxe/usr/x86_64-w64-mingw32.static/include/basetsd.h` but I can't include it for some unknown reason. I'm not sure if this is a MXE or djvulibre problem. I would suggest to disable this part of win api at all by declaring MMNODRV in djvulibre.

To do this unpack the attached patch
[djvulibre-2-fixes.zip](https://github.com/jsbien/djview4shapes/files/14072323/djvulibre-2-fixes.zip)
and place it to `djview4shapes/src/mxe/src/`. So there should be `djview4shapes/src/mxe/src/djvulibre-2-fixes.patch`    
Than call `./cross_compile.sh` again.

It's content is:
```
diff --git a/libdjvu/atomic.h b/libdjvu/atomic.h
index 84fc4f1..2a6390d 100644
--- a/libdjvu/atomic.h
+++ b/libdjvu/atomic.h
@@ -56,6 +56,7 @@ extern "C" {
 
 #if !defined(ATOMIC_MACROS) && defined(_WIN64)
 # define ATOMIC_MACROS "WIN64"
+# define MMNODRV // disable mmiscapi in MXE
 # include <windows.h>
 # define atomicIncrement(var) \
   (int)(InterlockedIncrement((LONG volatile*)(var)))
```

**Comment by jsbien** [comment]
Thank your very much for your quick help! It not only compiles but also works :-)
